travis:
  secure:
    BINSTAR_TOKEN: Hki2f85VOjjPllge7eFRLBr0f9J0X6nl/+8hi4tr5lgRktQ9z30i7kuApJ7H0+jiwyJRQT+XRnXN7vMktfQVdua6H7l+pfHaUUG3OnyqitU7m/XMQxbHOVw8padt4sS8ObxfC/8+rUR+eeP9ZGrRFEQHaecGy/o0TrgNYg6GoZnwcSeDPbOUqrdO4wf51wM0zCx1v0mU6Pa95ezBhaCCbZpeiuo+PubvpqtFkZHXyUa91g7QeUhFrq3jtj6KHfqGUMWwyy5u4wiWtdDdg7a3jn2MwYFEiYg5TVaH6QVB8aIfSca94UfKMQje/wTp6HgkzxW+QlvC348gPbab1Xtia8QpDZnrXaT3AtCtL/GF3JvVtBQ21Icy9ddePOgZKP2Av96ro4wI5kO8lMKtu4cxATVJ2NuVHQT/VRmN9TotOpA+7MotB3Qk1DOP0izKiaBuJ/dPIah1GP0/UX90y3AFcPWeCDQpTxBUsdkgnFbaeYlgA+7EPw9z9EcinWg2OL/Hjo2g8+6yFAUrYAoaAYmBqbY6C2ay08EXAiZm9pp6J0i989+vHeXCrVaUk6oO+hfxL34OT6YAUgtpZYxFAerpYu9YxNu7E5wNFkHwhacFF/7rFVLQegxP9Gjyh5DVXC8CL00aJj1Ge7z7OjqsDtugHEIGKjpvpx84H32LPkwo9aI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
