travis:
  secure:
    BINSTAR_TOKEN: ZGQiwFSTp/pWOjKLMX3Jkx1ILSzPfXYXbaHY9rrIAKe4AKD1UyojdePF/m7SeS82vhRAfd42pwTtg7a9rnb7zXBZnnPcTV2rqD3qzhEEUfmCqFnmsfoCmq3Z8b+9ypgwgEbanR5aknuNDgqGQXVJwQY30Q0kAA4DEtXHlh6wB1SL1lgi7CZwgoN3utPVbmJm2C+22oBXLk1Isqh705TRCQpqVFKxLgdte1GRTuutBSWike/f44je5f+B+lHSmsVoDEgWngS27JxL7TVnPKh3dYSry8/RYGoIQ/QCXmJw6uTNQ13MHHel9AUynU6s4PccNTSlW9Lr6OHpmIqrt6TzeJktSwyw5CJSj2K+1QnI85K9R7TnAfSXPEXBuY1qWHl0dx94rcWhnPhfgmE5Q4Cgs6LRGcGIj5jRNt4bKQ6uETGcLUMTlAj1hx1Zh/PdnMIJ0NUQJLnfMOixFLfvuvC8ffS5reI0DyGzAaVh/O9zxkGaWvEsH3nQW9xdd5wsgr46k/tykMiizYvWs+nPXTE1favLDZbXTQ9lcPaCP7m+HSdmuoMIwNQvYAAgNVLblIjEPYamp18xs8EWwJddLsfetoJP0AI0tow0MmBPvJxN6/ODr0hTxU/RuYid+tayKdJewbpyohrXGQ8i0kCQJXZsOZM1UYnFypz1TxNJhq2K9+E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
